--------------------------------------------------------
--  File created - Saturday-April-29-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table VISITE
--------------------------------------------------------

  CREATE TABLE "HR"."VISITE" 
   (	"MARQUE" VARCHAR2(20 BYTE), 
	"MATRICULE" VARCHAR2(15 BYTE), 
	"DATE_VT" VARCHAR2(20 BYTE), 
	"NATURE_DE_VISITE" VARCHAR2(20 BYTE), 
	"CODE_DE_CONFIRMATION" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.VISITE
SET DEFINE OFF;
Insert into HR.VISITE (MARQUE,MATRICULE,DATE_VT,NATURE_DE_VISITE,CODE_DE_CONFIRMATION) values ('ev','effe','2000/1/1','ssfz',1255);
Insert into HR.VISITE (MARQUE,MATRICULE,DATE_VT,NATURE_DE_VISITE,CODE_DE_CONFIRMATION) values ('efefe','efef','2000/1/1','grfgr',1234);
Insert into HR.VISITE (MARQUE,MATRICULE,DATE_VT,NATURE_DE_VISITE,CODE_DE_CONFIRMATION) values ('efagzerg','zrgr','2000/1/1','vff',8585);
Insert into HR.VISITE (MARQUE,MATRICULE,DATE_VT,NATURE_DE_VISITE,CODE_DE_CONFIRMATION) values ('fff','ddd','2000/1/1','dvds',1239);
Insert into HR.VISITE (MARQUE,MATRICULE,DATE_VT,NATURE_DE_VISITE,CODE_DE_CONFIRMATION) values ('ety(y','(e(y((','2000/1/1','normale',11);
--------------------------------------------------------
--  DDL for Index VISITE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."VISITE_PK" ON "HR"."VISITE" ("MATRICULE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table VISITE
--------------------------------------------------------

  ALTER TABLE "HR"."VISITE" ADD CONSTRAINT "VISITE_PK" PRIMARY KEY ("MATRICULE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
